version: '3.8'
services:
  db:
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${name_db}
      POSTGRES_USER: ${user_db}
      POSTGRES_PASSWORD: ${pass_db}
      POSTGRES_HOST: ${host_db}
      POSTGRES_PORT: ${port_db}
    ports:
      - "${port_db}:${port_db}"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
    depends_on:
      - db
    ports:
      - "${app_port}:${app_port}"

volumes:
  db_data:
    driver: local